# Generated by Django 5.2.5 on 2025-09-02 08:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfraCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone Font Awesome', max_length=50)),
            ],
            options={
                'verbose_name': 'Infraestrutura do Condomínio',
                'verbose_name_plural': 'Infraestruturas do Condomínio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('sobrado', 'Sobrado'), ('kitnet', 'Kitnet'), ('loft', 'Loft'), ('sala_comercial', 'Sala Comercial'), ('terreno', 'Terreno'), ('chacara', 'Chácara'), ('galpao', 'Galpão')], max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vendido', 'Vendido'), ('alugado', 'Alugado'), ('reservado', 'Reservado'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(default='SP', max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_util', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quartos', models.PositiveIntegerField(default=0)),
                ('suites', models.PositiveIntegerField(default=0)),
                ('banheiros', models.PositiveIntegerField(default=0)),
                ('vagas_garagem', models.PositiveIntegerField(default=0)),
                ('andar', models.CharField(blank=True, max_length=10)),
                ('ano_construcao', models.PositiveIntegerField(blank=True, null=True)),
                ('mobilia', models.CharField(choices=[('mobiliado', 'Mobiliado'), ('semimobiliado', 'Semimobiliado'), ('vazio', 'Vazio')], default='vazio', max_length=20)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('aceita_financiamento', models.BooleanField(default=True)),
                ('valor_condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_iptu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('infraestrutura', models.ManyToManyField(blank=True, to='core.infracondominio')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to='core.proprietario')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('eh_capa', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.imovel')),
            ],
            options={
                'verbose_name': 'Foto do Imóvel',
                'verbose_name_plural': 'Fotos do Imóvel',
                'ordering': ['ordem', 'criado_em'],
                'indexes': [models.Index(fields=['imovel', 'ordem'], name='core_fotoim_imovel__f7fd23_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrecoPorFinalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel'), ('temporada', 'Temporada')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diaria_minima', models.PositiveIntegerField(blank=True, help_text='Mínimo de diárias', null=True)),
                ('taxa_limpeza', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('capacidade_hospedes', models.PositiveIntegerField(blank=True, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='core.imovel')),
            ],
            options={
                'verbose_name': 'Preço por Finalidade',
                'verbose_name_plural': 'Preços por Finalidade',
                'indexes': [models.Index(fields=['finalidade', 'valor'], name='core_precop_finalid_b7f16d_idx')],
                'unique_together': {('imovel', 'finalidade')},
            },
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['status', 'tipo'], name='core_imovel_status_1ea982_idx'),
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['cidade', 'bairro'], name='core_imovel_cidade_006c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['quartos', 'banheiros'], name='core_imovel_quartos_a0254c_idx'),
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['criado_em'], name='core_imovel_criado__e3c3bc_idx'),
        ),
    ]
