# Generated by Django 5.2.5 on 2025-09-03 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('lead_frio', 'Lead Frio'), ('lead_morno', 'Lead Morno'), ('lead_quente', 'Lead Quente'), ('cliente_ativo', 'Cliente Ativo'), ('cliente_perdido', 'Cliente Perdido'), ('cliente_finalizado', 'Negócio Finalizado')], default='lead_frio', max_length=20)),
                ('origem', models.CharField(choices=[('site', 'Site'), ('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('indicacao', 'Indicação'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('placa', 'Placa'), ('outro', 'Outro')], default='site', max_length=20)),
                ('finalidade_interesse', models.CharField(blank=True, choices=[('venda', 'Comprar'), ('aluguel', 'Alugar'), ('temporada', 'Temporada'), ('venda_aluguel', 'Comprar ou Alugar')], max_length=20)),
                ('orcamento_max', models.DecimalField(blank=True, decimal_places=2, help_text='Orçamento máximo do cliente', max_digits=12, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o cliente e suas preferências')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultimo_contato', models.DateTimeField(blank=True, help_text='Data do último contato com o cliente', null=True)),
                ('imoveis_interesse', models.ManyToManyField(blank=True, related_name='clientes_interessados', to='core.imovel')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-atualizado_em'],
                'indexes': [models.Index(fields=['status'], name='core_client_status_369409_idx'), models.Index(fields=['origem'], name='core_client_origem_361b6d_idx'), models.Index(fields=['criado_em'], name='core_client_criado__5e2a16_idx'), models.Index(fields=['ultimo_contato'], name='core_client_ultimo__c6067b_idx')],
            },
        ),
    ]
